const ITEM_LABELS: Record<string, string> = {
  club: 'Дубинка',
  dagger: 'Кинжал',
  greatclub: 'Большая дубинка',
  handaxe: 'Ручной топор',
  javelin: 'Метательное копье',
  lighthammer: 'Легкий молот',
  mace: 'Булава',
  quarterstaff: 'Боевой посох',
  sickle: 'Серп',
  spear: 'Копье',
  lightcrossbow: 'Легкий арбалет',
  dart: 'Дротик',
  shortbow: 'Короткий лук',
  sling: 'Праща',
  battleaxe: 'Боевой топор',
  flail: 'Цеп',
  glaive: 'Глефа',
  greataxe: 'Секира',
  greatsword: 'Двуручный меч',
  halberd: 'Алебарда',
  lance: 'Пика всадника',
  longsword: 'Длинный меч',
  maul: 'Кувалда',
  morningstar: 'Моргенштерн',
  pike: 'Пика',
  rapier: 'Рапира',
  scimitar: 'Скимитар',
  shortsword: 'Короткий меч',
  trident: 'Трезубец',
  warpick: 'Боевой клевец',
  warhammer: 'Боевой молот',
  whip: 'Кнут',
  blowgun: 'Духовая трубка',
  handcrossbow: 'Ручной арбалет',
  heavycrossbow: 'Тяжелый арбалет',
  longbow: 'Длинный лук',
  net: 'Сеть',
  paddedarmor: 'Стеганая броня',
  leatherarmor: 'Кожаная броня',
  studdedleatherarmor: 'Проклепанная кожаная броня',
  hidearmor: 'Шкурная броня',
  chainshirt: 'Кольчужная рубаха',
  scalemail: 'Чешуйчатый доспех',
  breastplate: 'Кираса',
  halfplate: 'Полулаты',
  ringmail: 'Кольчатый доспех',
  chainmail: 'Кольчуга',
  splintarmor: 'Шинный доспех',
  platearmor: 'Латы',
  shield: 'Щит',
  backpack: 'Рюкзак',
  bedroll: 'Спальник',
  torch: 'Факел',
  rations: 'Сухой паек',
  waterskin: 'Бурдюк',
  ropehempen50feet: 'Пеньковая веревка (50 футов)',
  ropesilk50feet: 'Шелковая веревка (50 футов)',
  potionofhealing: 'Зелье лечения',
  healerskit: 'Набор лекаря',
  crowbar: 'Лом',
  tinderbox: 'Огниво',
  goldpieces: 'Золотые монеты',
};

const normalizeItemLabelKey = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '');

export const getItemLabel = (itemName: string | null | undefined): string => {
  if (!itemName) return '';
  return ITEM_LABELS[normalizeItemLabelKey(itemName)] ?? itemName;
};
